### ISSUE TITLE
Пропускает отрицательные значения в классе SavingAccount

### ISSUE THREAD

**Issue by ElenaLilu** [ElenaLilu/team_project#1]
# Описание
В классе SavingAccount пропускает отрицательные значения.

# Локация дефекта
https://github.com/ElenaLilu/team_project/blob/8669b6b3010d5703acb08374e7fb44e88829547d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23

# Шаги воспроизведения

1. Открыть [код тестов](src/main/java/ru/netology/javaqadiplom/SavingAccount.java)
2. Выставить значения:
InitialBalance  -2_000,
MinBalance    -1_000,
MaxBalance   -10_000,
 Rate                5
 account.add(-2_000)

3. Запустить тест
4. Посмотреть вывод в консоли 

# Ожидаемый результат 
Тест не проходит, обрушение сборки.

# Фактический результат 
Тест проходит. Ошибок нет

# Тест
https://github.com/ElenaLilu/team_project/blob/f88c95d470943da3ed9ae277e5c27c16ad35cbe5/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L118-L119

# Скриншот
![скрин_проект5](https://github.com/ElenaLilu/team_project/assets/135029773/91087f90-e189-46d0-a094-c6c2c46905d8)

 
# Окружение
* **Операционная система:** Windows 10 х64 19045.2965
* **IDE:** Intellij IDEA 2023.1.2 (Community edition)
* **Java:** 11 Eclipse Temurin version 11.0.19

**Comment by Khorolskaia-V** [comment]
Исправлено
