### ISSUE TITLE
В тестах класса SavingAccount не выбрасывается исключение вида IllegalArgumentException, когда минимальный баланс больше максимального

### ISSUE THREAD

**Issue by ElenaLilu** [ElenaLilu/team_project#2]
# Описание
В тестах SavingAccountTest при условии, что значения минимального баланса выше, чем значения у максимального баланса, не выбрасывается исключение вида IllegalArgumentException.

# Локация дефекта
https://github.com/ElenaLilu/team_project/blob/8669b6b3010d5703acb08374e7fb44e88829547d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Открыть [код классов](src/main/java/ru/netology/javaqadiplom/SavingAccount.java)
2. Выставить значения:
InitialBalance  2_000,
MinBalance    10_000,
MaxBalance   8_000,
 Rate                5
account.add(1)

3. Запустить тест
4. Посмотреть вывод в консоли 

# Ожидаемый результат 
Тест не проходит. Выбрасывает исключение вида IllegalArgumentException с текстом "Минимальный баланс не может быть больше максимального баланса".

# Фактический результат 
Тест не проходит по другой причине, без выбрасывания исключения вида IllegalArgumentException.

# Тест
https://github.com/ElenaLilu/team_project/blob/f88c95d470943da3ed9ae277e5c27c16ad35cbe5/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L44-L45

# Скриншот
![скрин_проект4](https://github.com/ElenaLilu/team_project/assets/135029773/5ee2471a-a848-4649-9050-17905529bada) 
 
# Окружение
* **Операционная система:** Windows 10 х64 19045.2965
* **IDE:** Intellij IDEA 2023.1.2 (Community edition)
* **Java:** 11 Eclipse Temurin version 11.0.19

**Comment by Khorolskaia-V** [comment]
Исправлено
