### ISSUE TITLE
Не производит сложения между начальным балансом и суммой пополнения в классе SavingAccount

### ISSUE THREAD

**Issue by ElenaLilu** [ElenaLilu/team_project#3]
# Описание
Выдаёт ошибку в классе SavingAccount при сложении значений начального баланса и суммы пополнения.

# Локация дефекта
https://github.com/ElenaLilu/team_project/blob/8669b6b3010d5703acb08374e7fb44e88829547d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72-L73

# Шаги воспроизведения

1. Открыть [код класса](src/main/java/ru/netology/javaqadiplom/SavingAccount.java)
2. Выставить значения:
InitialBalance  2_000,
MinBalance    1_000,
MaxBalance   10_000,
 Rate                5
 account.add(2_000)

3. Запустить тест
4. Посмотреть вывод в консоли 

# Ожидаемый результат 
Тест проходит. Баланс = 4_000

# Фактический результат 
Тест не проходит. В консоли баланс = 2_000

# Тест
https://github.com/ElenaLilu/team_project/blob/ea435658dd6843aeb7c8959b3437d7198750d1c5/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

 # Скриншот
![скрин_проект](https://github.com/ElenaLilu/team_project/assets/135029773/32c4375f-15d7-47bb-857a-f13efd229e13)

# Окружение
* **Операционная система:** Windows 10 х64 19045.2965
* **IDE:** Intellij IDEA 2023.1.2 (Community edition)
* **Java:** 11 Eclipse Temurin version 11.0.19

**Comment by Khorolskaia-V** [comment]
Исправлено
