### ISSUE TITLE
Выдаёт ошибку после корректного совершения покупки в SavingClass

### ISSUE THREAD

**Issue by ElenaLilu** [ElenaLilu/team_project#4]
# Описание
После корректного совершения покупки, где по условию сумма покупки может быть больше или равна нулю, система выдаёт ошибку некорректного состояния счёта.

# Локация дефекта
https://github.com/ElenaLilu/team_project/blob/8669b6b3010d5703acb08374e7fb44e88829547d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44-L46

# Шаги воспроизведения

1. Открыть [код тестов](src/main/java/ru/netology/javaqadiplom/SavingAccount.java)
2. Выставить значения:
InitialBalance  2_000,
MinBalance    1_000,
MaxBalance   10_000,
 Rate                5

3. Вызвать метод pay (boolean result = account.pay(1_500))

4. Запустить тест
5. Посмотреть вывод в консоли 

# Ожидаемый результат 
Тест проходит. Сборка не обрушается. Ошибок нет

# Фактический результат 
Тест не проходит. При корректных значениях в выводе, приводит к некорректному состоянию счета.

# Тест
https://github.com/ElenaLilu/team_project/blob/ea435658dd6843aeb7c8959b3437d7198750d1c5/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L209

# Скриншот
![скрин_пр](https://github.com/ElenaLilu/team_project/assets/135029773/34ad1a93-2236-4011-b4d6-2dadaf752a56)

 
# Окружение
* **Операционная система:** Windows 10 х64 19045.2965
* **IDE:** Intellij IDEA 2023.1.2 (Community edition)
* **Java:** 11 Eclipse Temurin version 11.0.19

**Comment by Khorolskaia-V** [comment]
Исправлено
