### ISSUE TITLE
При низком начальном балансе процентная ставка высчитывается некорректно

### ISSUE THREAD

**Issue by ElenaLilu** [ElenaLilu/team_project#5]
# Описание
В классе SavingAccount, где начальный баланс ниже 100, расчёт процентной ставки получается 0.

# Локация дефекта
https://github.com/ElenaLilu/team_project/blob/8669b6b3010d5703acb08374e7fb44e88829547d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88-L89

# Шаги воспроизведения

1. Открыть [код тестов](src/main/java/ru/netology/javaqadiplom/SavingAccount.java)
2. Выставить значения:
InitialBalance  77,
MinBalance    50,
MaxBalance   10_000,
 Rate                60
3. Вызвать метод yearChange
4. Запустить тест
5. Посмотреть вывод в консоли 

# Ожидаемый результат 
Тест проходит. Результат равен 46

# Фактический результат 
Тест не проходит. В результате даёт 0.

# Тест
https://github.com/ElenaLilu/team_project/blob/330814c0b14e0b1527f92a1ff8892311e86c2b13/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L298

# Скриншот
![скрин_проект3](https://github.com/ElenaLilu/team_project/assets/135029773/c8f2cf9c-f98f-4cfb-ac7a-aee1ea00ee9c)

 
# Окружение
* **Операционная система:** Windows 10 х64 19045.2965
* **IDE:** Intellij IDEA 2023.1.2 (Community edition)
* **Java:** 11 Eclipse Temurin version 11.0.19

**Comment by Khorolskaia-V** [comment]
Исправлено
